print('Hello World')
print("I've just added this in the command line repo")
print('This line added to show the staging area')
print('staging from the command line')
print('')
print('Staging from vs code')
print('')
print('Staging from desktop')
print('')
print('Introducing a merge conflict')